name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create the production build
      run: make basefiles npm-install npm-test npm-build
    - name: Switch to the branch that hosts the app
      run: git checkout gh-pages
    - name: Remote previous files
      run: git rm precache-* && git rm -r static
    - name: Copy files to the root
      run: cp -R build/* .
    - name: Stage file changes
      run: git add . 
    - name: Commit changes
      run: git commit -m "Updating deployment"
#    - name: Push changes
#      run: git push origin gh-pages
